/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  PdModal as PdModal
} from './components/pd-modal/pd-modal';

declare global {
  interface HTMLPdModalElement extends PdModal, HTMLStencilElement {
  }
  var HTMLPdModalElement: {
    prototype: HTMLPdModalElement;
    new (): HTMLPdModalElement;
  };
  interface HTMLElementTagNameMap {
    "pd-modal": HTMLPdModalElement;
  }
  interface ElementTagNameMap {
    "pd-modal": HTMLPdModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "pd-modal": JSXElements.PdModalAttributes;
    }
  }
  namespace JSXElements {
    export interface PdModalAttributes extends HTMLAttributes {
      title?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
