/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  MyModal as MyModal
} from './components/my-modal/my-modal';

declare global {
  interface HTMLMyModalElement extends MyModal, HTMLStencilElement {
  }
  var HTMLMyModalElement: {
    prototype: HTMLMyModalElement;
    new (): HTMLMyModalElement;
  };
  interface HTMLElementTagNameMap {
    "my-modal": HTMLMyModalElement;
  }
  interface ElementTagNameMap {
    "my-modal": HTMLMyModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-modal": JSXElements.MyModalAttributes;
    }
  }
  namespace JSXElements {
    export interface MyModalAttributes extends HTMLAttributes {
      title?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
